[package]
name = "libpsensor"
version = "0.1.0"
authors = ["iovxw <iovxw@outlook.com>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"

libpsensor-sys = { version="0.1", path="./libpsensor-sys" }
